"""Initial database structure for all NGO and Payment models

Revision ID: 347df4baa2a9
Revises: 
Create Date: 2025-10-01 20:50:37.341034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347df4baa2a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_ngos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ngo_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_ngos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('ngo_name', sa.String(length=100), nullable=True),
    sa.Column('ngo_type', sa.String(length=50), nullable=True),
    sa.Column('mission_statement', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('documents_path', sa.String(length=255), nullable=True),
    sa.Column('is_form_complete', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('temp_ngos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temp_ngos_email'), ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verified_ngos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ngo_type', sa.String(length=50), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_donations', sa.Float(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('verified_ngos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verified_ngos_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_verified_ngos_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_verified_ngos_ngo_type'), ['ngo_type'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['verified_ngos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_table('failed_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stripe_error_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('successful_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_charge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('successful_payments')
    op.drop_table('failed_payments')
    op.drop_table('payments')
    with op.batch_alter_table('verified_ngos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verified_ngos_ngo_type'))
        batch_op.drop_index(batch_op.f('ix_verified_ngos_name'))
        batch_op.drop_index(batch_op.f('ix_verified_ngos_location'))

    op.drop_table('verified_ngos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('temp_ngos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temp_ngos_email'))

    op.drop_table('temp_ngos')
    op.drop_table('rejected_ngos')
    # ### end Alembic commands ###
